// src/pages/blog/blog.data.js
// Entradas del blog. Cada post es contenido estático versionado en el repo:
// para publicar una entrada nueva basta con añadir un objeto aquí.
// `content` es una lista de bloques: h2 (subtítulo), p (párrafo), ul (lista).

export const POSTS = [
  {
    slug: "visa-estudios-vs-estancia-por-estudios",
    titulo: "Visa de Estudios vs. Estancia por Estudios: mismo permiso, distinto proceso",
    extracto:
      "Las dos vías llevan al mismo permiso para estudiar en España, pero se tramitan en lugares distintos y con tiempos distintos. Te explicamos cuál conviene según tu situación.",
    fecha: "2026-08-24",
    categoria: "Extranjería",
    minutos: 6,
    content: [
      { type: "p", text: "Si quieres estudiar en España más de 90 días necesitas una autorización de estancia por estudios. Lo que casi nadie te explica es que hay dos caminos para conseguirla, y elegir bien puede ahorrarte meses y mucho estrés." },
      { type: "h2", text: "Opción 1: Visa de Estudios (desde tu país)" },
      { type: "p", text: "Es la vía clásica: presentas tu solicitud ante el consulado español de tu país con la carta de admisión de tu centro de estudios, seguro médico, medios económicos y antecedentes penales apostillados. El consulado resuelve normalmente en 1 a 2 meses y viajas a España ya con tu visado pegado en el pasaporte." },
      { type: "ul", items: [
        "Se tramita ante el consulado español de tu país de residencia.",
        "Necesitas antecedentes penales y certificado médico apostillados.",
        "Entras a España con el estatus de estudiante ya resuelto.",
      ] },
      { type: "h2", text: "Opción 2: Estancia por Estudios (ya en España)" },
      { type: "p", text: "La segunda vía consiste en entrar a España como turista (los latinoamericanos de la mayoría de países no necesitan visado para estancias cortas) y, estando en situación regular, presentar la solicitud de estancia por estudios ante la Oficina de Extranjería. Debes presentarla con suficiente antelación y cumplir requisitos equivalentes." },
      { type: "ul", items: [
        "Se tramita ante extranjería, ya estando en España.",
        "Evitas la cita consular, que en algunos países tarda meses.",
        "Requiere planificar bien los plazos: hay ventanas concretas para presentar.",
      ] },
      { type: "h2", text: "¿Cuál te conviene?" },
      { type: "p", text: "Depende de tus tiempos, de la carga de tu consulado y de cuándo empieza tu programa. En una primera asesoría revisamos tu calendario académico, tu situación documental y te decimos con claridad cuál de los dos procesos maximiza tus probabilidades." },
    ],
  },
  {
    slug: "residencia-nomada-digital-espana",
    titulo: "Residencia de Nómada Digital en España: requisitos reales en 2026",
    extracto:
      "Trabajar en remoto desde España legalmente es posible con la residencia de nómada digital. Es un proceso rápido, pero con requisitos exigentes. Esto es lo que de verdad piden.",
    fecha: "2026-08-24",
    categoria: "Extranjería",
    minutos: 5,
    content: [
      { type: "p", text: "La Ley de Startups abrió la puerta a que teletrabajadores de empresas extranjeras vivan legalmente en España. La residencia de nómada digital es de los procesos más rápidos de extranjería, pero no es para todos: los requisitos económicos y laborales son altos." },
      { type: "h2", text: "Los requisitos que sí o sí debes cumplir" },
      { type: "ul", items: [
        "Trabajar para una empresa extranjera (o tener clientes mayoritariamente fuera de España si eres freelance).",
        "Antigüedad mínima de 3 meses con esa empresa y que la empresa lleve al menos 1 año operando.",
        "Ingresos de al menos el 200% del salario mínimo interprofesional español.",
        "Titulación universitaria o experiencia profesional mínima de 3 años.",
        "Seguro médico y antecedentes penales limpios.",
      ] },
      { type: "h2", text: "¿Por qué se considera un proceso rápido?" },
      { type: "p", text: "Si la solicitud se presenta en España, la administración debe resolver en unos 20 días hábiles, y aplica el silencio administrativo positivo: si no responden en plazo, se entiende concedida. Además la residencia inicial es de hasta 3 años, renovable, y computa para la nacionalidad." },
      { type: "h2", text: "El error más común" },
      { type: "p", text: "Presentar contratos o certificados laborales que no acreditan bien la relación con la empresa extranjera. La mayoría de denegatorias que vemos vienen de documentación laboral mal armada, no de incumplir requisitos. Una revisión profesional del expediente antes de presentar marca la diferencia." },
    ],
  },
  {
    slug: "nacionalidad-espanola-latinoamericanos-2-anos",
    titulo: "Nacionalidad española para latinoamericanos: la vía de los 2 años",
    extracto:
      "Los ciudadanos de países iberoamericanos pueden pedir la nacionalidad española con solo 2 años de residencia legal. Te contamos cómo funciona el proceso completo.",
    fecha: "2026-08-24",
    categoria: "Nacionalidad",
    minutos: 6,
    content: [
      { type: "p", text: "Mientras la regla general exige 10 años de residencia legal en España para pedir la nacionalidad, los nacionales de países iberoamericanos —incluido todo Latinoamérica— solo necesitan 2 años. Es una de las mayores ventajas migratorias que tenemos como latinoamericanos." },
      { type: "h2", text: "Qué cuenta (y qué no) como residencia legal" },
      { type: "p", text: "Los 2 años deben ser de residencia legal, continuada e inmediatamente anterior a la solicitud. Ojo: la estancia por estudios NO computa como residencia a estos efectos — por eso muchos estudiantes hacen primero la modificatoria de estudiante a residente, y desde ahí empiezan a contar sus 2 años." },
      { type: "h2", text: "Los exámenes: CCSE y DELE" },
      { type: "ul", items: [
        "CCSE (Prueba Cervantes): examen de conocimientos constitucionales y socioculturales de España.",
        "DELE A2 o superior: solo para quienes no tienen el español como lengua materna — los latinoamericanos hispanohablantes están exentos.",
      ] },
      { type: "h2", text: "El proceso paso a paso" },
      { type: "ul", items: [
        "Reunir certificados: antecedentes penales del país de origen apostillados, empadronamiento, TIE vigente.",
        "Aprobar la prueba CCSE del Instituto Cervantes.",
        "Presentar la solicitud telemática ante el Ministerio de Justicia.",
        "Jura o promesa de la nacionalidad una vez concedida, e inscripción en el Registro Civil.",
      ] },
      { type: "p", text: "Los plazos de resolución varían, pero un expediente bien presentado desde el inicio evita los requerimientos que suelen añadir meses al proceso." },
    ],
  },
  {
    slug: "master-en-espana-guia-de-pasos",
    titulo: "Estudiar un Máster en España: la guía de pasos completa",
    extracto:
      "Desde elegir universidad hasta aterrizar en España: el orden correcto de los pasos, los plazos reales y los errores que retrasan la admisión.",
    fecha: "2026-08-24",
    categoria: "Asesoría educativa",
    minutos: 7,
    content: [
      { type: "p", text: "Cada año acompañamos a decenas de latinoamericanos a estudiar su máster en España. El proceso es totalmente alcanzable, pero tiene un orden y unos plazos que conviene respetar. Esta es la ruta completa." },
      { type: "h2", text: "1. Elige programa con estrategia (12-9 meses antes)" },
      { type: "p", text: "España tiene más de 1,100 másteres oficiales entre universidades públicas y privadas. La clave no es postular a muchos, sino a los correctos: los que aceptan tu titulación, encajan con tu perfil y tienen costos que puedes asumir. Las públicas pueden costar desde 1,500 € el año para extranjeros en algunas comunidades." },
      { type: "h2", text: "2. Prepara la documentación académica (9-6 meses antes)" },
      { type: "ul", items: [
        "Título y certificado de notas apostillados.",
        "En algunos casos, equivalencia de notas medias del Ministerio de Universidades.",
        "CV académico y carta de motivación adaptados al programa.",
      ] },
      { type: "h2", text: "3. Postula y asegura tu plaza (6-4 meses antes)" },
      { type: "p", text: "Cada universidad tiene su propio calendario de admisión, y muchas abren varios periodos. Postular en el primer periodo aumenta tus opciones de plaza y de beca. Al ser admitido, la mayoría pide una reserva de plaza para emitir tu carta de admisión." },
      { type: "h2", text: "4. Tramita tu visado (4-2 meses antes)" },
      { type: "p", text: "Con la carta de admisión inicias el visado de estudios en tu consulado, o planificas la estancia por estudios desde España. Aquí entran el seguro médico, los medios económicos y los antecedentes penales apostillados." },
      { type: "h2", text: "5. Aterriza con todo en orden" },
      { type: "p", text: "Ya en España: TIE (toma de huellas), empadronamiento y, si vas a trabajar en prácticas, alta en la seguridad social. Nada de esto es difícil si llega en el orden correcto — y para eso estamos." },
    ],
  },
  {
    slug: "homologacion-titulo-universitario-espana",
    titulo: "Homologación y equivalencia de tu título universitario en España",
    extracto:
      "¿Necesitas homologar tu título para estudiar o trabajar en España? No siempre. Te explicamos cuándo hace falta, qué vía elegir y cuánto tarda de verdad.",
    fecha: "2026-08-24",
    categoria: "Asesoría educativa",
    minutos: 5,
    content: [
      { type: "p", text: "Una de las dudas más frecuentes de quienes migran a España con estudios terminados: ¿tengo que homologar mi título? La respuesta corta: depende de para qué lo quieras usar." },
      { type: "h2", text: "¿Cuándo NO necesitas homologar?" },
      { type: "p", text: "Para estudiar un máster oficial, la mayoría de universidades españolas aceptan títulos latinoamericanos sin homologar: basta una comprobación de equivalencia que hace la propia universidad. Si tu objetivo es solo estudiar un postgrado, probablemente no necesites homologación." },
      { type: "h2", text: "¿Cuándo SÍ la necesitas?" },
      { type: "ul", items: [
        "Para ejercer una profesión regulada (medicina, enfermería, abogacía, arquitectura, etc.).",
        "Para oposiciones y empleo público.",
        "Cuando un empleador exige el título homologado o la equivalencia oficial.",
      ] },
      { type: "h2", text: "Homologación vs. Equivalencia" },
      { type: "p", text: "La homologación equipara tu título a uno español concreto que habilita para una profesión regulada. La equivalencia lo reconoce a nivel académico (área y nivel de grado) sin habilitar profesión. Elegir mal la vía es el error que más expedientes retrasa." },
      { type: "h2", text: "Plazos reales" },
      { type: "p", text: "Los expedientes ante el Ministerio pueden tardar bastantes meses, y cualquier defecto documental (apostillas, traducciones, certificados de plan de estudios) genera requerimientos que suman más tiempo. Presentar el expediente completo y bien armado desde el día uno es la mejor inversión." },
      { type: "h2", text: "¿Y la secundaria?" },
      { type: "p", text: "Si lo que necesitas es homologar tus estudios de secundaria al Bachillerato español (por ejemplo para estudiar un grado o una FP), el trámite es distinto y también lo gestionamos." },
    ],
  },
  {
    slug: "formacion-profesional-espana-carrera-tecnica",
    titulo: "Formación Profesional en España: la vía rápida que casi nadie mira",
    extracto:
      "Dos años, prácticas en empresas desde el primer año, matrícula subvencionada y permiso para trabajar 30 horas semanales. La FP española es una de las mejores puertas de entrada.",
    fecha: "2026-08-24",
    categoria: "Asesoría educativa",
    minutos: 6,
    content: [
      { type: "p", text: "Cuando alguien piensa en estudiar en España, piensa en un máster. Pero hay una vía que suele encajar mejor con muchos perfiles y que pasa desapercibida: la Formación Profesional. Son estudios técnicos de dos años, con prácticas en empresas desde el primer año y una empleabilidad altísima." },
      { type: "h2", text: "Por qué la FP es tan interesante" },
      { type: "ul", items: [
        "Costos de matrícula subvencionados en centros públicos.",
        "Prácticas en empresas desde el primer año.",
        "Acceso directo a la universidad al terminar.",
        "Válida para tu visa de estudios en España.",
        "Permiso para trabajar hasta 30 horas a la semana.",
      ] },
      { type: "h2", text: "Qué puedes estudiar" },
      { type: "p", text: "La oferta cubre prácticamente todos los sectores: administración y gestión, comercio y marketing, informática y comunicaciones, sanidad, imagen personal, hostelería y turismo, electricidad y electrónica, energía y agua, fabricación mecánica, edificación y obra civil, industrias alimentarias, actividades físicas y deportivas, artes gráficas, vídeo y fotografía, transporte y mantenimiento de vehículos, y varias más." },
      { type: "h2", text: "El requisito que marca el calendario" },
      { type: "p", text: "Para acceder necesitas haber terminado la secundaria y homologar tus estudios al Bachillerato español. Este es el paso que más tarda, así que es el que debe arrancar primero: mientras la homologación se resuelve, el volante de presentación ya te permite matricularte en centros de FP." },
      { type: "h2", text: "Calendario orientativo" },
      { type: "ul", items: [
        "Trámite de constancia de estudios legalizada: al cierre del año anterior.",
        "Inicio de la homologación escolar: enero–febrero.",
        "Resolución de la homologación: marzo–abril.",
        "Postulación a centros: mayo–junio.",
        "Respuesta de los centros: junio–julio.",
        "Inicio del trámite de visa: julio–agosto.",
        "Inicio de clases: septiembre–octubre.",
      ] },
      { type: "p", text: "Si tu objetivo es llegar a España con una formación práctica, empleable y económicamente accesible, la FP merece estar sobre la mesa antes de descartarla." },
    ],
  },
  {
    slug: "denegacion-visa-estudios-recurso-reposicion",
    titulo: "Te denegaron la visa de estudios: qué hacer (y qué no) desde el día uno",
    extracto:
      "Una denegación no es el final del camino, pero los plazos para recurrir son cortos. Esto es lo que hay que revisar antes de decidir entre apelar o cambiar de estrategia.",
    fecha: "2026-08-24",
    categoria: "Extranjería",
    minutos: 5,
    content: [
      { type: "p", text: "Recibir una resolución de denegación es un golpe duro, sobre todo cuando ya tienes la carta de admisión y las clases empiezan en pocas semanas. La buena noticia: no todo está perdido. La mala: los plazos para reaccionar son cortos y perentorios." },
      { type: "h2", text: "Lo primero: leer la causa real de la denegación" },
      { type: "p", text: "Las denegaciones no son todas iguales. Puede tratarse de una acreditación económica insuficiente, de un seguro médico que no cumple la cobertura exigida, de dudas sobre el propósito de la estancia o de un defecto formal en la documentación. La causa determina si el recurso tiene recorrido o no." },
      { type: "h2", text: "Qué implica un recurso de reposición bien hecho" },
      { type: "ul", items: [
        "Análisis jurídico de la resolución de denegación.",
        "Elaboración del escrito de recurso, argumentando sobre la causa concreta.",
        "Revisión por abogados con conocimiento del consulado que resolvió.",
        "Presentación del recurso en plazo ante el Consulado de España.",
        "Seguimiento del expediente hasta la resolución.",
      ] },
      { type: "h2", text: "Cuándo el recurso NO es el mejor camino" },
      { type: "p", text: "A veces la vía más rápida y segura no es insistir ante el consulado, sino reconducir el caso hacia una estancia por estudios solicitada ya en España. Es una decisión estratégica que depende de tus fechas de clase, de la causa de la denegación y de tu situación documental." },
      { type: "h2", text: "El principio que aplicamos" },
      { type: "p", text: "Solo asumimos casos viables. Si tras analizar tu resolución vemos que el recurso no prospera, te lo decimos y trabajamos la alternativa que sí tiene posibilidades reales. Preferimos una conversación honesta a un expediente condenado desde el inicio." },
    ],
  },
  {
    slug: "calendario-estudiar-espana-2026-2027",
    titulo: "Calendario para estudiar en España 2026/2027: cuándo hacer cada cosa",
    extracto:
      "El error más caro no es elegir mal la universidad: es empezar tarde. Este es el calendario real de un proceso de máster, grado o FP, mes a mes.",
    fecha: "2026-08-24",
    categoria: "Asesoría educativa",
    minutos: 6,
    content: [
      { type: "p", text: "Casi todos los procesos que se complican tienen la misma causa de fondo: arrancaron tarde. Los trámites académicos y migratorios españoles tienen ventanas concretas, y perder una puede significar esperar un año entero. Este es el orden real de las cosas." },
      { type: "h2", text: "Máster oficial" },
      { type: "ul", items: [
        "Trámite de documentación universitaria: entre noviembre y enero.",
        "Postulación: noviembre–enero, con nuevas fases en junio y septiembre.",
        "Resultados de admisión: entre marzo y agosto según la fase.",
        "Preinscripción: de junio a septiembre.",
        "Inicio del trámite de visa: julio–agosto.",
        "Inicio de clases: septiembre–octubre.",
      ] },
      { type: "h2", text: "Grado universitario" },
      { type: "p", text: "El grado añade dos pasos que alargan mucho el calendario: la homologación del bachillerato y las pruebas de acceso PCE/EBAU de la UNED. La homologación se inicia lo antes posible; las pruebas se inscriben entre febrero y mayo, se rinden en junio y en julio se hace la preinscripción universitaria." },
      { type: "h2", text: "Formación Profesional" },
      { type: "p", text: "La homologación escolar arranca en enero o febrero y se resuelve entre marzo y abril. Las postulaciones a centros van de mayo a junio, la respuesta llega entre junio y julio, la visa se inicia en julio o agosto y las clases empiezan en octubre." },
      { type: "h2", text: "El consejo que damos siempre" },
      { type: "p", text: "Reúne y legaliza tus documentos académicos antes de saber a dónde vas a postular. Título, certificado de notas y carga horaria apostillados sirven para la postulación, para la homologación y para el visado. Tenerlos listos con antelación es lo que convierte un proceso apretado en uno cómodo." },
      { type: "p", text: "Y si vas a intentar una beca, postula en las primeras fases: las convocatorias más interesantes, incluidas las exclusivas para extranjeros, cierran mucho antes del inicio de clases." },
    ],
  },
];

export const getPost = (slug) => POSTS.find((p) => p.slug === slug);
